// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQvQSdZkqhZWK_vm5o5u0g46gRYupWTFo',
    appId: '1:1089326893210:web:5a6b552293acd2194a7723',
    messagingSenderId: '1089326893210',
    projectId: 'tickynotes1',
    authDomain: 'tickynotes1.firebaseapp.com',
    storageBucket: 'tickynotes1.appspot.com',
    measurementId: 'G-4E9R6YNMWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd-lU3Pmkmo-MxAySs1mpmuHdXT-tAfMo',
    appId: '1:1089326893210:android:eeb3d1a6a7d2cbdc4a7723',
    messagingSenderId: '1089326893210',
    projectId: 'tickynotes1',
    storageBucket: 'tickynotes1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIUIPK6RTNk0-w2CZgqzY9SU9UebKl1tY',
    appId: '1:1089326893210:ios:3cb767b805db50894a7723',
    messagingSenderId: '1089326893210',
    projectId: 'tickynotes1',
    storageBucket: 'tickynotes1.appspot.com',
    iosBundleId: 'com.example.tickynotes1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIUIPK6RTNk0-w2CZgqzY9SU9UebKl1tY',
    appId: '1:1089326893210:ios:3cb767b805db50894a7723',
    messagingSenderId: '1089326893210',
    projectId: 'tickynotes1',
    storageBucket: 'tickynotes1.appspot.com',
    iosBundleId: 'com.example.tickynotes1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQvQSdZkqhZWK_vm5o5u0g46gRYupWTFo',
    appId: '1:1089326893210:web:75f53b34065a04f34a7723',
    messagingSenderId: '1089326893210',
    projectId: 'tickynotes1',
    authDomain: 'tickynotes1.firebaseapp.com',
    storageBucket: 'tickynotes1.appspot.com',
    measurementId: 'G-CV4EZSEQDJ',
  );
}
